version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-211-210-149.compute-1.amazonaws.com
            database: d35302pmrkk31p
            user: ayxepurqewdfdi
            password: fe629f6ab3c97f39d3874661c9b7703fde9ed92ebcd304c4ca05472fc8ca9bbd
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true